### ISSUE TITLE
Give $red accessible contrast ratio

### ISSUE THREAD

**Issue by johnfrenchxyz** [duckduckgo/duckduckgo-colors#4]
I decided to open this as an issue, rather than a PR, because I expect there to be at least a little bit of discussion.

Currently, even on a white background, the `$red` variable as it stands at `#de5833` gives a contrast ratio of 3.78:1.  The recommended minimum contrast ratio by WCAG 2.0 (AA) is 4.5:1 for normal text and 3:1 for large text.

If you changed it to `$red: #d14822;` it would meet the recommended minimum and make the entire template more accessible for users with visual disabilities.  Just food for thought!

**Comment by moollaza** [comment]
Thanks. Our design team is aware of the required contrast ratios and we're now taking it into account as we update elements of the site.
